# Generated by Django 5.0.1 on 2024-03-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(blank=True, max_length=23),
        ),
    ]
